# Numpy Scipy

In [1]:
import numpy as np

## Arrays
Los arrays en NumPy son estructuras de datos similares a listas, pero permiten almacenar y manipular grandes cantidades de datos numéricos de manera eficiente. Un array de NumPy puede tener una o más dimensiones y soporta operaciones matemáticas vectorizadas.

En el ejemplo:
- `a = np.array([1, 2, 3])` crea un array de una dimensión con los valores `[1, 2, 3]`.
- `a[0] = 5` modifica el primer elemento del array, cambiando su valor a 5, por lo que el array resultante es `[5, 2, 3]`.

Los arrays permiten realizar operaciones rápidas y eficientes sobre grandes conjuntos de datos, lo que los hace ideales para cálculos científicos y análisis de datos.

La salida muestra información sobre el array `a`:

- `<class 'numpy.ndarray'>`: Indica que `a` es un array de NumPy.
- `(3,)`: Es la forma (shape) del array, lo que significa que tiene 3 elementos en una sola dimensión.
- `1 2 3`: Son los valores originales del array antes de modificar el primer elemento.
- `[5 2 3]`: Es el array después de cambiar el primer elemento a 5.

In [3]:
a = np.array([1, 2, 3]) # Create a rank1 array
print(type(a), a.shape, a[0], a[1], a[2])
a[0] = 5 # Change an element of the array
print(a)

<class 'numpy.ndarray'> (3,) 1 2 3
[5 2 3]


In [ ]:
b = np.array([[1, 2, 3], [4, 5, 6]]) #Create a rank2 array
print(b)

[[1 2 3]
 [4 5 6]]


In [5]:
print(b.shape)
print(b[0, 0], b[0, 1], b[1, 0])

(2, 3)
1 2 4


In [6]:
a = np.zeros((2, 2))  # Create an array of all zeros
print(a)
print("Array shape:", a.shape)

[[0. 0.]
 [0. 0.]]
Array shape: (2, 2)


In [7]:
b = np.ones((1, 2))  # Create an array of all ones
print(b)
print("Array shape:", b.shape)

[[1. 1.]]
Array shape: (1, 2)


In [8]:
c = np.full((2, 2), 7)  # Create a constant array
print("Array shape:", c.shape)
print(c)

Array shape: (2, 2)
[[7 7]
 [7 7]]


In [9]:
d = np.eye(2)  # Create a 2x2 identity matrix
print("Array shape:", d.shape)
print(d)

Array shape: (2, 2)
[[1. 0.]
 [0. 1.]]


In [10]:
e = np.random.random((2, 2))  # Create an array filled with random values
print(e)
print("Array shape:", e.shape)

[[0.94353661 0.47370134]
 [0.20733563 0.84032213]]
Array shape: (2, 2)


## Tensores
Los tensores son estructuras de datos multidimensionales que generalizan los conceptos de escalares (0 dimensiones), vectores (1 dimensión) y matrices (2 dimensiones) a cualquier número de dimensiones. En NumPy, un tensor se representa como un array de N dimensiones (`ndarray`). Los tensores permiten almacenar y manipular grandes volúmenes de datos en múltiples dimensiones, lo que es fundamental en áreas como el álgebra lineal, la computación científica y el aprendizaje profundo.

Por ejemplo, el tensor `T` definido en este notebook es un array tridimensional de forma `(3, 3, 3)`, donde cada elemento puede accederse mediante tres índices: `T[i, j, k]`.

In [11]:
from numpy import array

T = array([
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ],
    [
        [11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]
    ],
    [
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]
    ]
])

print(T.shape)
print(T)

(3, 3, 3)
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]

 [[21 22 23]
  [24 25 26]
  [27 28 29]]]


In [12]:
# Suma de tensores
A = T
B = T
C = A + B
print(C)


[[[ 2  4  6]
  [ 8 10 12]
  [14 16 18]]

 [[22 24 26]
  [28 30 32]
  [34 36 38]]

 [[42 44 46]
  [48 50 52]
  [54 56 58]]]


## Array indexing

In [15]:
# Crear un array de rango 2 con forma (3, 4)
arr = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

# Usar slicing para extraer el subarray de las dos primeras filas y columnas 1 y 2
# Resultado esperado:
# [[2 3]
#  [6 7]]
subarr = arr[:2, 1:3]
print(subarr)

[[2 3]
 [6 7]]


In [17]:
# Mostrar el valor original de a[0, 1]
print(arr[0, 1])

# Modificar el valor de b[0, 0]
# Nota: En este caso, 'a' y 'b' NO comparten memoria, así que esto no afecta a 'a'
subarr[0, 0] = 77

# Mostrar nuevamente el valor de a[0, 1] para ver si cambió
print(arr[0, 1])

2
77


In [19]:
# Crear un array de rango 2 con forma (3, 4)
a = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


### Selección de filas en arrays NumPy: diferencias entre rank 1 y rank 2

En NumPy, la forma en que seleccionas filas de un array puede afectar la dimensionalidad (el "rango") del resultado:

- `row_r1 = a[1, :]`: Selecciona la segunda fila de `a` como un array de una dimensión (rank 1).  
    - Resultado: `array([5, 6, 7, 8])`
    - Forma: `(4,)`

- `row_r2 = a[1:2, :]`: Selecciona la segunda fila pero mantiene la dimensión de filas, devolviendo un array de dos dimensiones (rank 2) con una sola fila.  
    - Resultado: `array([[5, 6, 7, 8]])`
    - Forma: `(1, 4)`

- `row_r3 = a[[1], :]`: Selecciona la segunda fila usando indexación avanzada, también devuelve un array de dos dimensiones (rank 2) con una sola fila.  
    - Resultado: `array([[5, 6, 7, 8]])`
    - Forma: `(1, 4)`

**Resumen:**  
- Usar `a[1, :]` da un vector 1D.
- Usar `a[1:2, :]` o `a[[1], :]` da una matriz 2D con una sola fila.

Esto es importante porque algunas operaciones de NumPy requieren arrays de cierta dimensionalidad.

In [20]:
row_r1 = a[1, :]        # Rank 1 view of the second row of a
row_r2 = a[1:2, :]      # Rank 2 view of the second row of a
row_r3 = a[[1], :]      # Rank 2 view of the second row of a

print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)
print(row_r3, row_r3.shape)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[[5 6 7 8]] (1, 4)


In [ ]:
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]

# Podemos hacer la misma distinción al acceder a columnas de un array:
col_r1 = a[:, 1]        # Rank 1: columna como vector 1D
col_r2 = a[:, 1:2]      # Rank 2: columna como matriz 2D

print(col_r1, col_r1.shape)
print()
print(col_r2, col_r2.shape)

[ 2  6 10] (3,)

[[ 2]
 [ 6]
 [10]] (3, 1)


## Indexación de arrays enteros:

In [22]:
# Creamos un array de ejemplo
a = np.array([[1, 2],
              [3, 4],
              [5, 6]])

# Ejemplo de indexación con arrays de enteros.
# El array resultante tendrá forma (3,)
indices_fila = [0, 1, 2]
indices_columna = [0, 1, 0]
resultado = a[indices_fila, indices_columna]
print(resultado)  # [1 4 5]

# El ejemplo anterior es equivalente a:
equivalente = np.array([a[0, 0], a[1, 1], a[2, 0]])
print(equivalente)  # [1 4 5]

[1 4 5]
[1 4 5]


In [23]:
# Ejemplo: reutilizar el mismo elemento usando indexación con arrays de enteros
elementos_repetidos = a[[0, 0], [1, 1]]
print(elementos_repetidos)  # Salida: [2 2]

# Equivalente usando acceso directo a los elementos
equivalente = np.array([a[0, 1], a[0, 1]])
print(equivalente)  # Salida: [2 2]

[2 2]
[2 2]


Un truco útil con la indexación de matrices de números enteros es seleccionar o mutar un elemento de cada fila de una matriz:

In [24]:
# Crear un nuevo array del cual seleccionaremos elementos
a = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12]
])

print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [25]:
# Crear un array de índices para seleccionar elementos de cada fila
b = np.array([0, 2, 0, 1])

# Seleccionar un elemento de cada fila de 'a' usando los índices en 'b'
# np.arange(4) genera los índices de fila: [0, 1, 2, 3]
# b indica la columna a seleccionar en cada fila
seleccion = a[np.arange(4), b]

print(seleccion)  # Imprime: [ 1  6  7 11]

[ 1  6  7 11]


In [26]:
# Mutar un elemento de cada fila de 'a' usando los índices en 'b'
# np.arange(4) genera los índices de fila: [0, 1, 2, 3]
# b indica la columna a modificar en cada fila

a[np.arange(4), b] += 10

print(a)

[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


## Indexación booleana de matrices
La indexación booleana de matrices permite seleccionar elementos arbitrarios de una matriz. Con frecuencia, este tipo de indexación se utiliza para seleccionar los elementos de una matriz que satisfacen alguna condición. He aquí un ejemplo:

In [29]:
a = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])

# Creamos una máscara booleana para encontrar los elementos de 'a' mayores que 2
bool_idx = (a > 2)

# Mostramos la máscara booleana resultante
print(bool_idx)

[[False False]
 [ True  True]
 [ True  True]]


In [30]:
# Usamos indexación booleana para construir un array de una dimensión
# con los elementos de 'a' que corresponden a los valores True de 'bool_idx'
elementos_filtrados = a[bool_idx]
print(elementos_filtrados)

# También podemos hacer todo en una sola línea:
print(a[a > 2])

[3 4 5 6]
[3 4 5 6]
